# Create a new release when a tag starting with `v` is pushed to the repository
on:
  push:
    tags:
      - 'v*' 

name: Create Release

env:
  PROJECT_NAME: test-release
  # Release is a prerelease if the tag contains RC or rc
  PRERELEASE: ${{ contains(github.ref, 'RC') || contains(github.ref, 'rc') }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Create Release Notes'
        id: create-release-notes
        run: |
          echo "::set-output name=release-notes::$(./create-release-notes.sh)"

      - name: 'Create Release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.PROJECT_NAME }} ${{ github.ref }}
          body: ${{ steps.create-release-notes.outputs.release-notes }}
          draft: false
          prerelease: ${{ env.PRERELEASE }} 
